Main: Main.o
	g++ ./*.cpp -o main -std=c++14  -lsfml-graphics -lsfml-window -lsfml-system -lpthread

Main.o: Main.cpp
	g++ -c -std=c++14 ./*.cpp  -lsfml-graphics -lsfml-window -lsfml-system -lpthread
